# Generated by Django 4.1.4 on 2023-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
