# Generated by Django 4.1.4 on 2023-11-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='decaid',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='tshirt',
            field=models.TextField(default='none'),
        ),
    ]
