# Generated by Django 4.1.4 on 2023-11-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_decaid_user_grade_user_tshirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='bloodtype',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_cell',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_first_name',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_last_name',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='partners',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='physician',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='physicianAddress',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user',
            name='physicianPhone',
            field=models.TextField(default='noun'),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.TextField(default='none'),
        ),
    ]
