# Generated by Django 4.1.4 on 2023-11-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_bloodtype_user_cell_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insurance_number',
            field=models.TextField(default='none'),
        ),
    ]
